development:
  adapter: postgresql
  database: save_animals_development

test:
  adapter: postgresql
  database: save_animals_test

production:
  adapter: postgresql
  database: save_animals_production
  encoding: unicode
  pool: 5

